#! /bin/bash

if [ "$1" = "triggered" ]
then
	if [ "$2" = "/opt/ont/minknow/ont-python/lib" ]
	then
		logger "fast5upload: Triggered for ONT Python"
	fi
fi

mkdir -p /var/lib/mlstverse
chown root:root /var/lib/mlstverse

/opt/ont/minknow/ont-python/bin/python3 -m pip install watchdog

if [ $(head -c 1 /etc/mlstverse/fast5upload.conf) == '{' ]
then
	printf 'You are using an old version of fast5upload config.\n'
	printf 'We will attempt to fix the config format automatically the next time you start fast5upload.\n'
	printf 'If anything did not work as expected, please contact support.\n'
fi

systemctl --system daemon-reload
